spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/maybedo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true
        generate_statistics: true

logging.level:
  org.hibernate.SQL: debug